### ISSUE TITLE
UI rewrite

### ISSUE THREAD

**Issue by crosborn** [LA1TV/Roses-CasparCG-Graphics#12]
Fix: rewrite the UI to fix the following issues: 
make general functions available on all screens (fix them at the top?,
fix multi user support so changes can be viewed in all clients

**Comment by moschopsuk** [comment]
> fix multi user support so changes can be viewed in all clients

This will require rewriting everything to handle the 2-way state changes, it will simple be easier to start a new rather than trying to path it around.

**Comment by benjaminkay93** [comment]
@crosborn  im gonna close this off, as its not something that will ever be done in this package, but it is something we need to bare in mind in the future
