### ISSUE TITLE
Feature request: UI graphics live indicator

### ISSUE THREAD

**Issue by crosborn** [LA1TV/Roses-CasparCG-Graphics#14]
Fix: add an indicator to show which graphics are live. Maybe a red dot on each tab that is live next to the name?

**Comment by benjaminkay93** [comment]
I'm working on this just so people are aware :)

**Comment by joshhodgson** [comment]
Any progress, ben?

**Comment by benjaminkay93** [comment]
nope, no update on this im afraid, will check back in 11 months with another update ;)

**Comment by benjaminkay93** [comment]
(its rude not to answer a question aha)

**Comment by benjaminkay93** [comment]
https://github.com/LA1TV/Roses-CasparCG-Graphics/pull/94
