### ISSUE TITLE
Feature Request: full width lower thirds

### ISSUE THREAD

**Issue by crosborn** [LA1TV/Roses-CasparCG-Graphics#15]
add full width lower thirds

**Comment by danleedham** [comment]
How would you like this to work? Would you like a tick box to make them full-width or something else? At current they'll be a minimum of 20% the div unless the words are longer.

**Comment by crosborn** [comment]
Can there be another button alongside "left" and "right" for "full width"?

**Comment by danleedham** [comment]
This is done on branch FullW-3r
