### ISSUE TITLE
Fix: Grid Colours

### ISSUE THREAD

**Issue by crosborn** [LA1TV/Roses-CasparCG-Graphics#19]
Fix: Recolour grid so it isn't so hideous

**Comment by danleedham** [comment]
I'm going to try make it so that you can make it as hideous as you wish in the client.

**Comment by danleedham** [comment]
I mean having an admin panel to choose the two main colors would be sick, but not sure if that's inside the scope of Roses graphics...

**Comment by benjaminkay93** [comment]
i was gonna build in 3 options, a lancaster colouring, a york coloring and a blue one, so that it can be decided by the director / graphics op

**Comment by danleedham** [comment]
This is just waiting for the grid to be fixed on Caspar.
