### ISSUE TITLE
Fix: General live 

### ISSUE THREAD

**Issue by crosborn** [LA1TV/Roses-CasparCG-Graphics#22]
live button doesn't work when clock isn't on. either make it work or grey out option when clock is not on

**Comment by benjaminkay93** [comment]
need to grey out, the clock should always be on?? in my opinion its your reference if your cutting up footage post event, and also if we go on the basis that its always there in every stream then it will always be covered if any footage wants to be used elsewhere, (live should follow clock right?)

**Comment by moschopsuk** [comment]
I would say remove both the clock and live symbol as they really don't serve a purpose. Plus they don't convey any actually useful information.

**Comment by benjaminkay93** [comment]
remove i don't think we need to, maybe only use them on studio streams and not sports though? 
and then only have the bug on sports

**Comment by moschopsuk** [comment]
Lets face it they will be watched on a site that will say they are live, and on devices that tell you the time. So why should we also show a clock that behind the clock shown on their device.

The only place where you see them is on 24 hour news channels that are likely to be shown on large screens in public areas.

Also if you publish to Facebook it will over them up with a live pulse icon.

**Comment by benjaminkay93** [comment]
the clock kinda makes sense, and I've just thought... because of the nature of the event people can be watching in any timezone, so i think it should stay, esp if we are having a graphic built for showing stream times and matches live times, so they can adjust it for there timezone easier

**Comment by moschopsuk** [comment]
Thats fair enough I removed the live clock and bug in v2 anyway for this issue. I would have considered keeping the live, as that can be shown in par with a location, so if you are jumping between locations it should live at, (Arena, Pitch 1, Pitch 2).

Regarding timezones I disagree as if they are already planning to watch it, they already know the time difference, so why tell them again ?

**Comment by benjaminkay93** [comment]
live would deffonitly helps in transmission if it was used correctly for that purpose, and 9 times out of 10 i agree the clock is bit pointless

**Comment by danleedham** [comment]
I'd like to add the location box next to the live to show where a OS is live from / was it was live from (similar to news / sports channels) as Luke mentions above. I'm happy to code this, unless there'd be outcry against it? I do like the live bug to separate from longer VTs of previous matches - maybe we should allow it to be changed to things like 'Yesterday', 'last night' or whatever the director fancies? I also think it's nice to have the time for on VOD, plus many devices that tell the time you may have in fullscreen... I think ripping it out all together is a backward step. If you're directing, exec-produce and don't like it you don't have to use it :)

**Comment by moschopsuk** [comment]
Just to add on, my reason to remove it is based on the fact we are not a 24 hour channel.
When LA1TV sort out the TX system and we stream 24 hours, and it allows us to switch from programming to a live stream then I think that when having a bug that says we are live makes sense.
