### ISSUE TITLE
Archery doesn't work

### ISSUE THREAD

**Issue by crosborn** [LA1TV/Roses-CasparCG-Graphics#32]
Make it work?????

**Comment by benjaminkay93** [comment]
@DomBelcher can you have a look, may just have cocked up the pull request as there was merge conflicts 👍

**Comment by danleedham** [comment]
I can get this to work inside the browser. Looks quite good actually!

**Comment by TMannall** [comment]
It worked when I tried it too, but we aren't covering it at Roses and the scoring in the package is for a different style of competing.

**Comment by TMannall** [comment]
@DomBelcher Did you ever check if this worked? If so we can close this issue.
