### ISSUE TITLE
Add Waterpolo sport

### ISSUE THREAD

**Issue by TMannall** [LA1TV/Roses-CasparCG-Graphics#34]
Implement support for the Waterpolo sport

**Comment by benjaminkay93** [comment]
gonna pick this up, i believe its 4 quarters of 8 minutes each, but need to find out, should be easy enough though :D

**Comment by benjaminkay93** [comment]
https://github.com/LA1TV/Roses-CasparCG-Graphics/pull/95

**Comment by benjaminkay93** [comment]
We have waterpolo now, so im closing this.
