### ISSUE TITLE
Add Handball Sport

### ISSUE THREAD

**Issue by TMannall** [LA1TV/Roses-CasparCG-Graphics#36]
Implement support for the Handball sport

**Comment by danleedham** [comment]
I'd argue you can use either Netball or Football for this.

Time counts up 
2 halves of 30 min (standard) . Overtime is 2x5min. Penalty 7m throws if still tied. 
Each goal = 1 point
Conceding team takes throw-off

Reference: https://www.youtube.com/watch?v=Z4pNq2cr40s http://www.ihf.info/upload/pdf-download/rules_english.pdf
