### ISSUE TITLE
Data Format for Historical/Predefined Data

### ISSUE THREAD

**Issue by danleedham** [LA1TV/Roses-CasparCG-Graphics#86]
I've started collecting data from previous Roses (such as who won which year, which sports were won by which uni etc) as well as fixtures across the weekend so that we can have single button graphics displayed, similar to the 'constituencies' from Elections 2017.

As such rather than diving straight in, who's got the best way of defining the data we use?

I'd go with something simple like json files for each dataset that's predefined (who won American football in 2008 isn't going to change!), only because that's how I did it for the Elections, such as: 
https://github.com/NaSTAuk/General-Election-Graphics/blob/master/public/data/2017_candidates.json

As I'm a thoughtful chap, I'd rather the team decide than I suggest something that is useless for everyone else!

**Comment by stephenrob** [comment]
In theory this data is available in Roses Live APIs (if we get access/develop in time). However, we can define the format we would like this in before we get the APIs.

@moschopsuk might have a good recommendation in terms of vocabulary to use from BBC Sport.

If you have some sample fields of information you want or categories we can look into.

I'd say something similar to below for the yearly winners:

```
{
  "1970": {
    "won_by": "Lancaster",
    "score": {
      "lancaster": 100,
      "york": "50"
    }
  }
....
}
```

or

```
{
 [{
    "year": 1970,
    "won_by": "Lancaster",
    "score": {
      "lancaster": 100,
      "york": "50"
    }
  }....
]}
```

**Comment by danleedham** [comment]
```
[
  {
    "date": "2018-04-28",
    "time": "10:00:00",
    "sport": "Rowing",
    "group": "men's senior 4",
    "points": 2,
    "location": "University Boat House",
    "warmup-time": "10:00:00",
    "warmup-location": "University Boat House"
  },
  {
    "date": "2018-04-28",
    "time": "10:10:00",
    "sport": "Rowing",
    "group": "men's novice 8",
    "points": 1,
    "location": "University Boat House",
    "warmup-time": "10:10:00",
    "warmup-location": "University Boat House"
  },
```

I'd like an additional value of 'being broadcast'... but I'll let someone else do that!

**Comment by stephenrob** [comment]
For this years events this is all available from Roses Live but we need the API access / develop proper APIs. Format is near enough there though i'd say maybe some nested objects over a flat object.

**Comment by danleedham** [comment]
I'll pop my data into: `Google Drive / Roses 2018 / On-Screen Graphics / Data` for now...

**Comment by danleedham** [comment]
Thanks @stephenrob This is now solved.
