### ISSUE TITLE
Suggestion: Reskin Graphics Feel

### ISSUE THREAD

**Issue by danleedham** [LA1TV/Roses-CasparCG-Graphics#87]
Shall I start the conversation about how we should update the look and feel of the graphics for 2018?

I'd LOVE to move towards brush graphics for everything major.... (such as using these as a background images for Lower Thirds: https://roseslive.co.uk/imgs/followlive.png https://roseslive.co.uk/imgs/heading2.png)

I've then seen graphics like this with the 3D effect: 

![dy0d1lwx4aep-go](https://user-images.githubusercontent.com/12582998/38360085-67cc0934-38c1-11e8-806b-c03e08d82608.jpg)
![dztlg1zvqaajryl](https://user-images.githubusercontent.com/12582998/38360088-67e8dafa-38c1-11e8-81d6-bbcb77aa44c0.jpg)

Thoughts?

How about we move towards the Red / White roses for smaller logos (ie in the score bar at the top left) as: https://roseslive.co.uk/imgs/rose_red.png https://roseslive.co.uk/imgs/rose_white.png , keeping the large logos for the bigger central graphics?

Comments below...

**Comment by peskdale** [comment]
I’m told the 3D logo is just YUSU trying to make the Lancs Roses logo more interesting for their advertising.

**Comment by stephenrob** [comment]
Some discussion around a flat UI has been discussed in PR #91
